export const PREMIUM_PLANS = [
  { key: 'premium_1d', label: '⭐ 1 Kun', duration: 1, unit: 'days', stars: 5 },
  { key: 'premium_7d', label: '⭐ 7 Kun', duration: 7, unit: 'days', stars: 25 },
  { key: 'premium_30d', label: '⭐ 30 Kun', duration: 30, unit: 'days', stars: 80 },
  { key: 'premium_90d', label: '⭐ 90 Kun', duration: 90, unit: 'days', stars: 200 },
  { key: 'premium_180d', label: '⭐ 180 Kun', duration: 180, unit: 'days', stars: 350 },
  { key: 'premium_365d', label: '⭐ 365 Kun', duration: 365, unit: 'days', stars: 600 },
  { key: 'premium_lifetime', label: '💎 Lifetime', duration: 0, unit: 'lifetime', stars: 1500 },
] as const

export const DEFAULT_CATEGORIES = [
  { name: 'Action', slug: 'action', icon: '🎬' },
  { name: 'Comedy', slug: 'comedy', icon: '😂' },
  { name: 'Horror', slug: 'horror', icon: '👻' },
  { name: 'Drama', slug: 'drama', icon: '🎭' },
  { name: 'Sci-Fi', slug: 'sci-fi', icon: '🚀' },
  { name: 'Anime', slug: 'anime', icon: '🎌' },
  { name: 'Cartoon', slug: 'cartoon', icon: '🧸' },
  { name: 'Documentary', slug: 'documentary', icon: '📽' },
  { name: 'Sport', slug: 'sport', icon: '⚽' },
  { name: 'Family', slug: 'family', icon: '👨‍👩‍👧‍👦' },
] as const

export const ADMIN_PERMISSIONS = {
  dashboard: { label: '📊 Dashboard', default: true },
  movies: { label: '🎬 Kino boshqaruvi', default: true },
  series: { label: '🎞 Serial boshqaruvi', default: true },
  categories: { label: '📂 Kategoriyalar', default: true },
  channels: { label: '📢 Kanallar', default: true },
  users: { label: '👥 Foydalanuvchilar', default: false },
  premium: { label: '💎 Premium', default: true },
  payments: { label: '⭐ To\'lovlar', default: false },
  broadcast: { label: '📨 Broadcast', default: true },
  stats: { label: '📈 Statistika', default: true },
  moderators: { label: '🛡 Moderatorlar', default: false },
  settings: { label: '⚙ Sozlamalar', default: false },
  logs: { label: '📝 Loglar', default: true },
} as const

export const ROLE_LEVELS = {
  owner: 100,
  superadmin: 90,
  admin: 70,
  moderator: 50,
  support: 30,
  user: 0,
} as const

export const PAGINATION = {
  pageSize: 10,
  maxPageSize: 20,
} as const

export const PREMIUM_REMINDERS = [
  { label: '3 kun qoldi', daysBefore: 3 },
  { label: '1 kun qoldi', daysBefore: 1 },
  { label: '6 soat qoldi', hoursBefore: 6 },
] as const

export const EMOJIS = {
  movie: '🎬',
  series: '🎞',
  premium: '💎',
  star: '⭐',
  fire: '🔥',
  heart: '❤️',
  search: '🔍',
  settings: '⚙',
  stats: '📊',
  admin: '🛡',
  broadcast: '📨',
  category: '📂',
  channel: '📢',
  user: '👤',
  users: '👥',
  calendar: '📅',
  clock: '⏱',
  globe: '🌍',
  check: '✅',
  cross: '❌',
  back: '🔙',
  next: '➡️',
  prev: '⬅️',
  top: '🏆',
  trending: '📈',
  views: '👁',
  download: '📥',
  save: '💾',
  history: '📋',
  recommend: '🤖',
  language: '🗣',
  rating: '⭐',
  year: '📆',
  country: '📍',
  episode: '📺',
  season: '📦',
  notification: '🔔',
  warning: '⚠️',
  error: '🚫',
  success: '✅',
  info: 'ℹ️',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  pencil: '✏️',
  trash: '🗑',
  add: '➕',
  remove: '➖',
  refresh: '🔄',
  mute: '🔇',
  unmute: '🔊',
}

export const ERROR_MESSAGES = {
  notSubscribed: 'Botdan foydalanish uchun quyidagi kanallarga obuna bo\'ling:',
  banned: 'Siz botdan foydalanishdan bloklangansiz.',
  premiumOnly: 'Bu funksiya faqat 💎 Premium foydalanuvchilar uchun.',
  adminOnly: 'Bu funksiya faqat adminlar uchun.',
  movieNotFound: 'Kino topilmadi.',
  seriesNotFound: 'Serial topilmadi.',
  invalidCode: 'Noto\'g\'ri kod formati.',
  paymentFailed: 'To\'lov amalga oshmadi. Qayta urinib ko\'ring.',
  rateLimit: 'So\'rovlar cheklanishiga yetdingiz. Birozdan so\'ng urinib ko\'ring.',
  maintenance: 'Bot texnik ishlar uchun vaqtincha to\'xtatilgan.',
} as const
